version: '3'

services:
    angry-shortener:
        build:
            context: .
        container_name: angry-shortener
        environment:
            - PORT=3000
            - NODE_ENV=production
            - DATABASE_URL=mongodb://root:example@mongodb:27017/shorten
